#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR="$(mktemp -d)"

cleanup() {
  rm -rf "$TMP_DIR"
}

trap cleanup EXIT

make_repo() {
  local repo_root="$1"
  mkdir -p "$repo_root"
  cp -R "$ROOT_DIR/scripts" "$repo_root/scripts"
  mkdir -p "$repo_root/codex-memory" "$repo_root/codex-learning" "$repo_root/codex-logs" "$repo_root/queues" "$repo_root/projects"
}

REPO_ROOT="$TMP_DIR/repo"
EXTERNAL_PROJECT_ROOT="$TMP_DIR/superheld"
make_repo "$REPO_ROOT"
mkdir -p "$EXTERNAL_PROJECT_ROOT/.codex-agent"

cat >"$REPO_ROOT/codex-memory/tasks.json" <<'EOF'
{
  "tasks": [
    {
      "id": "task-138-reduce-registry-pressure",
      "title": "Reduce registry pressure",
      "project": "codex-agent-system",
      "status": "pending_approval",
      "strategy_template": "self_improvement",
      "source_task_id": "self-improve",
      "task_intent": {
        "source": "self-improve",
        "objective": "Reduce registry pressure",
        "project": "codex-agent-system",
        "category": "performance",
        "context_hint": "Task registry exceeded the shared pressure threshold."
      },
      "execution_task": "[self-improve:medium] Reduce registry pressure -- Task registry exceeded the shared pressure threshold.",
      "created_at": "2026-03-25T08:40:00Z",
      "updated_at": "2026-03-25T08:40:05Z",
      "history": [
        {
          "at": "2026-03-25T08:40:05Z",
          "action": "create",
          "from_status": "",
          "to_status": "pending_approval",
          "project": "codex-agent-system",
          "queue_task": "[self-improve:medium] Reduce registry pressure -- Task registry exceeded the shared pressure threshold.",
          "note": "Auto-generated by self-improve engine."
        }
      ]
    }
  ]
}
EOF

: >"$REPO_ROOT/codex-memory/tasks.log"

cat >"$REPO_ROOT/codex-learning/metrics.json" <<EOF
{
  "success_rate": 0.8,
  "recent_success_rate": 0.78,
  "timeout_failure_rate": 0.04,
  "first_pass_success_rate": 0.76,
  "approved_tasks": 0,
  "pending_approval_tasks": 1,
  "approved_backlog": 0,
  "task_registry_payload_bytes": 984518,
  "task_registry_pressure_detected": true,
  "task_registry_pressure_primary_surface": "dashboard_read_path",
  "task_registry_pressure_sources": [
    {
      "project": "superheld",
      "file": "$EXTERNAL_PROJECT_ROOT/.codex-agent/tasks.json",
      "payload_bytes": 852069
    },
    {
      "project": "codex-agent-system",
      "file": "$REPO_ROOT/codex-memory/tasks.json",
      "payload_bytes": 132449
    }
  ],
  "retry_churn_detected": false,
  "strategy_saturation_detected": false,
  "external_signal_status": "fresh",
  "total_tasks": 10
}
EOF

cat >"$REPO_ROOT/codex-learning/external-signals.json" <<'EOF'
{}
EOF

python3 - "$REPO_ROOT/codex-learning/metrics.json" <<'PY'
import os
import sys
import time

metrics_path = sys.argv[1]
future = time.time() + 60
os.utime(metrics_path, (future, future))
PY

(
  cd "$REPO_ROOT"
  IMPROVEMENT_COOLDOWN_SECONDS=0 bash scripts/self-improve.sh codex-agent-system >/dev/null
)

task_summary="$(
  jq -r '
    .tasks
    | map(select(.id == "task-138-reduce-registry-pressure"))
    | first
    | [
        .status,
        .shelved_reason,
        .history[-1].action,
        .history[-1].to_status
      ] | @tsv
  ' "$REPO_ROOT/codex-memory/tasks.json"
)"
if [ "$task_summary" != $'shelved\tauto-shelved: registry pressure is now cross-project only; local registry is 129KB (<500KB)\tauto_shelve\tshelved' ]; then
  echo "unexpected resolved registry pressure task summary: $task_summary" >&2
  exit 1
fi

artifact_summary="$(
  jq -r '
    [
      (.gating.retired_resolved_pending_tasks // 0),
      (.metrics_snapshot.registry_pressure_scope // ""),
      ((.metrics_snapshot.local_registry_bytes // 0) | tostring)
    ] | @tsv
  ' "$REPO_ROOT/codex-learning/self-improve-run.json"
)"
if [ "$artifact_summary" != $'1\tcross_project\t132449' ]; then
  echo "unexpected self-improve artifact registry retirement summary: $artifact_summary" >&2
  exit 1
fi

echo "self improve resolved registry pressure task test passed"
