#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR="$(mktemp -d)"

cleanup() {
  rm -rf "$TMP_DIR"
}

trap cleanup EXIT

make_repo() {
  local repo_root="$1"
  mkdir -p "$repo_root"
  cp -R "$ROOT_DIR/scripts" "$repo_root/scripts"
  mkdir -p "$repo_root/codex-memory" "$repo_root/codex-learning" "$repo_root/codex-logs" "$repo_root/queues" "$repo_root/projects"
}

REPO_ROOT="$TMP_DIR/repo"
make_repo "$REPO_ROOT"

cat >"$REPO_ROOT/codex-memory/tasks.json" <<'EOF'
{
  "tasks": [
    {
      "id": "task-137-improve-timeout-diagnostic-coverage",
      "title": "Improve timeout diagnostic coverage",
      "project": "codex-agent-system",
      "status": "pending_approval",
      "strategy_template": "self_improvement",
      "source_task_id": "self-improve",
      "task_intent": {
        "source": "self-improve",
        "objective": "Improve timeout diagnostic coverage",
        "project": "codex-agent-system",
        "category": "stability",
        "context_hint": "Only 21% of failure records carry diagnostic context while zero-step timeouts are elevated."
      },
      "execution_task": "[self-improve:critical] Improve timeout diagnostic coverage -- Only 21% of failure records carry diagnostic context while zero-step timeouts are elevated.",
      "created_at": "2026-03-25T08:15:00Z",
      "updated_at": "2026-03-25T08:15:05Z",
      "history": [
        {
          "at": "2026-03-25T08:15:05Z",
          "action": "create",
          "from_status": "",
          "to_status": "pending_approval",
          "project": "codex-agent-system",
          "queue_task": "[self-improve:critical] Improve timeout diagnostic coverage -- Only 21% of failure records carry diagnostic context while zero-step timeouts are elevated.",
          "note": "Auto-generated by self-improve engine."
        }
      ]
    }
  ]
}
EOF

: >"$REPO_ROOT/codex-memory/tasks.log"

cat >"$REPO_ROOT/codex-learning/metrics.json" <<'EOF'
{
  "success_rate": 0.82,
  "recent_success_rate": 0.79,
  "timeout_failure_rate": 0.06,
  "first_pass_success_rate": 0.78,
  "retry_classification_coverage": 0.87,
  "retry_classified_count": 54,
  "retry_total_count": 62,
  "diagnostic_coverage": 0.86,
  "recent_diagnostic_coverage": 0.84,
  "failures_with_diagnostic": 43,
  "total_failure_records": 50,
  "approved_tasks": 0,
  "pending_approval_tasks": 1,
  "approved_backlog": 0,
  "task_registry_pressure_bytes": 64000,
  "strategy_saturation": false,
  "zero_step_timeout_rate": 0.05
}
EOF

cat >"$REPO_ROOT/codex-learning/external-signals.json" <<'EOF'
{}
EOF

python3 - "$REPO_ROOT/codex-learning/metrics.json" <<'PY'
import os
import sys
import time

metrics_path = sys.argv[1]
future = time.time() + 60
os.utime(metrics_path, (future, future))
PY

(
  cd "$REPO_ROOT"
  IMPROVEMENT_COOLDOWN_SECONDS=0 bash scripts/self-improve.sh codex-agent-system >/dev/null
)

task_summary="$(
  jq -r '
    .tasks
    | map(select(.id == "task-137-improve-timeout-diagnostic-coverage"))
    | first
    | [
        .status,
        .shelved_reason,
        .history[-1].action,
        .history[-1].to_status
      ] | @tsv
  ' "$REPO_ROOT/codex-memory/tasks.json"
)"
if [ "$task_summary" != $'shelved\tauto-shelved: timeout diagnostic coverage recovered to 86% (43/50)\tauto_shelve\tshelved' ]; then
  echo "unexpected resolved timeout diagnostic task summary: $task_summary" >&2
  exit 1
fi

artifact_summary="$(
  jq -r '
    [
      (.gating.retired_resolved_pending_tasks // 0)
    ] | @tsv
  ' "$REPO_ROOT/codex-learning/self-improve-run.json"
)"
if [ "$artifact_summary" != $'1' ]; then
  echo "unexpected self-improve artifact timeout retirement summary: $artifact_summary" >&2
  exit 1
fi

echo "self improve resolved timeout diagnostic task test passed"
