#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR="$(mktemp -d)"

cleanup() {
  rm -rf "$TMP_DIR"
}

trap cleanup EXIT

make_repo() {
  local repo_root="$1"
  mkdir -p "$repo_root"
  cp -R "$ROOT_DIR/scripts" "$repo_root/scripts"
  mkdir -p "$repo_root/codex-memory" "$repo_root/codex-learning" "$repo_root/codex-logs" "$repo_root/queues" "$repo_root/projects"
}

REPO_ROOT="$TMP_DIR/repo"
make_repo "$REPO_ROOT"

cat >"$REPO_ROOT/codex-memory/tasks.json" <<'EOF'
{
  "tasks": [
    {
      "id": "task-141-improve-first-pass-success-rate",
      "title": "Improve first-pass success rate",
      "project": "codex-agent-system",
      "status": "pending_approval",
      "strategy_template": "self_improvement",
      "source_task_id": "self-improve",
      "task_intent": {
        "source": "self-improve",
        "objective": "Improve first-pass success rate",
        "project": "codex-agent-system",
        "category": "stability",
        "context_hint": "Tasks fail even on first attempt (12% first-pass success)."
      },
      "execution_task": "[self-improve:critical] Improve first-pass success rate -- Tasks fail even on first attempt (12% first-pass success).",
      "created_at": "2026-03-25T08:55:00Z",
      "updated_at": "2026-03-25T08:55:05Z",
      "history": [
        {
          "at": "2026-03-25T08:55:05Z",
          "action": "create",
          "from_status": "",
          "to_status": "pending_approval",
          "project": "codex-agent-system",
          "queue_task": "[self-improve:critical] Improve first-pass success rate -- Tasks fail even on first attempt (12% first-pass success).",
          "note": "Auto-generated by self-improve engine."
        }
      ]
    },
    {
      "id": "task-142-drain-approved-task-backlog",
      "title": "Drain approved task backlog",
      "project": "codex-agent-system",
      "status": "pending_approval",
      "strategy_template": "self_improvement",
      "source_task_id": "self-improve",
      "task_intent": {
        "source": "self-improve",
        "objective": "Drain approved task backlog",
        "project": "codex-agent-system",
        "category": "performance",
        "context_hint": "16 approved tasks are waiting while the queue is idle."
      },
      "execution_task": "[self-improve:low] Drain approved task backlog -- 16 approved tasks are waiting while the queue is idle.",
      "created_at": "2026-03-25T09:05:00Z",
      "updated_at": "2026-03-25T09:05:05Z",
      "history": [
        {
          "at": "2026-03-25T09:05:05Z",
          "action": "create",
          "from_status": "",
          "to_status": "pending_approval",
          "project": "codex-agent-system",
          "queue_task": "[self-improve:low] Drain approved task backlog -- 16 approved tasks are waiting while the queue is idle.",
          "note": "Auto-generated by self-improve engine."
        }
      ]
    }
  ]
}
EOF

: >"$REPO_ROOT/codex-memory/tasks.log"

cat >"$REPO_ROOT/codex-learning/metrics.json" <<'EOF'
{
  "success_rate": 0.84,
  "recent_success_rate": 0.8,
  "timeout_failure_rate": 0.03,
  "first_pass_success_rate": 0.72,
  "retry_classification_coverage": 0.9,
  "retry_classified_count": 18,
  "retry_total_count": 20,
  "approved_tasks": 2,
  "pending_approval_tasks": 0,
  "approved_backlog": 2,
  "queued_tasks": 1,
  "running_tasks": 0,
  "queue_starvation_detected": false,
  "task_registry_pressure_bytes": 64000,
  "strategy_saturation": false,
  "zero_step_timeout_rate": 0.0,
  "external_signal_status": "fresh"
}
EOF

cat >"$REPO_ROOT/codex-learning/external-signals.json" <<'EOF'
{}
EOF

python3 - "$REPO_ROOT/codex-learning/metrics.json" <<'PY'
import os
import sys
import time

metrics_path = sys.argv[1]
future = time.time() + 60
os.utime(metrics_path, (future, future))
PY

(
  cd "$REPO_ROOT"
  IMPROVEMENT_COOLDOWN_SECONDS=0 bash scripts/self-improve.sh codex-agent-system >/dev/null
)

first_pass_summary="$(
  jq -r '
    .tasks
    | map(select(.id == "task-141-improve-first-pass-success-rate"))
    | first
    | [
        .status,
        .shelved_reason,
        .history[-1].action,
        .history[-1].to_status
      ] | @tsv
  ' "$REPO_ROOT/codex-memory/tasks.json"
)"
if [ "$first_pass_summary" != $'shelved\tauto-shelved: first-pass success rate recovered to 72%\tauto_shelve\tshelved' ]; then
  echo "unexpected resolved first-pass task summary: $first_pass_summary" >&2
  exit 1
fi

backlog_summary="$(
  jq -r '
    .tasks
    | map(select(.id == "task-142-drain-approved-task-backlog"))
    | first
    | [
        .status,
        .shelved_reason,
        .history[-1].action,
        .history[-1].to_status
      ] | @tsv
  ' "$REPO_ROOT/codex-memory/tasks.json"
)"
if [ "$backlog_summary" != $'shelved\tauto-shelved: approved backlog recovered to 2 active approvals (<= 8)\tauto_shelve\tshelved' ]; then
  echo "unexpected resolved backlog-drain task summary: $backlog_summary" >&2
  exit 1
fi

artifact_summary="$(
  jq -r '
    [
      (.gating.retired_resolved_pending_tasks // 0),
      (.gating.retired_obsolete_pending_tasks // 0)
    ] | @tsv
  ' "$REPO_ROOT/codex-learning/self-improve-run.json"
)"
if [ "$artifact_summary" != $'2\t0' ]; then
  echo "unexpected self-improve artifact retirement summary: $artifact_summary" >&2
  exit 1
fi

echo "self improve resolved backlog focus tasks test passed"
