#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR="$(mktemp -d)"

cleanup() {
  rm -rf "$TMP_DIR"
}

trap cleanup EXIT

make_repo() {
  local repo_root="$1"
  mkdir -p "$repo_root"
  cp -R "$ROOT_DIR/scripts" "$repo_root/scripts"
  mkdir -p "$repo_root/codex-memory" "$repo_root/codex-learning" "$repo_root/codex-logs" "$repo_root/queues" "$repo_root/projects"
}

REPO_ROOT="$TMP_DIR/repo"
make_repo "$REPO_ROOT"

cat >"$REPO_ROOT/codex-memory/tasks.json" <<'EOF'
{
  "tasks": [
    {
      "id": "task-139-refresh-stale-external-signals",
      "title": "Refresh stale external signals",
      "project": "codex-agent-system",
      "status": "pending_approval",
      "strategy_template": "self_improvement",
      "source_task_id": "self-improve",
      "task_intent": {
        "source": "self-improve",
        "objective": "Refresh stale external signals",
        "project": "codex-agent-system",
        "category": "learning",
        "context_hint": "External signals were stale."
      },
      "execution_task": "[self-improve:low] Refresh stale external signals -- External signals were stale.",
      "created_at": "2026-03-25T09:00:00Z",
      "updated_at": "2026-03-25T09:00:05Z",
      "history": [
        {
          "at": "2026-03-25T09:00:05Z",
          "action": "create",
          "from_status": "",
          "to_status": "pending_approval",
          "project": "codex-agent-system",
          "queue_task": "[self-improve:low] Refresh stale external signals -- External signals were stale.",
          "note": "Auto-generated by self-improve engine."
        }
      ]
    }
  ]
}
EOF

: >"$REPO_ROOT/codex-memory/tasks.log"

cat >"$REPO_ROOT/codex-learning/metrics.json" <<'EOF'
{
  "success_rate": 0.82,
  "recent_success_rate": 0.8,
  "timeout_failure_rate": 0.04,
  "first_pass_success_rate": 0.78,
  "retry_classification_coverage": 0.87,
  "retry_classified_count": 54,
  "retry_total_count": 62,
  "approved_tasks": 0,
  "pending_approval_tasks": 1,
  "approved_backlog": 0,
  "task_registry_pressure_bytes": 64000,
  "strategy_saturation": false,
  "external_signal_status": "fresh",
  "fresh_external_signal_count": 2,
  "latest_external_signal_source": "OpenAI Python releases",
  "total_tasks": 10
}
EOF

cat >"$REPO_ROOT/codex-learning/external-signals.json" <<'EOF'
{}
EOF

python3 - "$REPO_ROOT/codex-learning/metrics.json" <<'PY'
import os
import sys
import time

metrics_path = sys.argv[1]
future = time.time() + 60
os.utime(metrics_path, (future, future))
PY

(
  cd "$REPO_ROOT"
  IMPROVEMENT_COOLDOWN_SECONDS=0 bash scripts/self-improve.sh codex-agent-system >/dev/null
)

task_summary="$(
  jq -r '
    .tasks
    | map(select(.id == "task-139-refresh-stale-external-signals"))
    | first
    | [
        .status,
        .shelved_reason,
        .history[-1].action,
        .history[-1].to_status
      ] | @tsv
  ' "$REPO_ROOT/codex-memory/tasks.json"
)"
if [ "$task_summary" != $'shelved\tauto-shelved: external signals refreshed; 2 fresh signals from OpenAI Python releases\tauto_shelve\tshelved' ]; then
  echo "unexpected resolved external signals task summary: $task_summary" >&2
  exit 1
fi

artifact_summary="$(
  jq -r '
    [
      (.gating.retired_resolved_pending_tasks // 0),
      (.metrics_snapshot.external_signal_status // ""),
      ((.metrics_snapshot.fresh_external_signal_count // 0) | tostring),
      (.metrics_snapshot.latest_external_signal_source // "")
    ] | @tsv
  ' "$REPO_ROOT/codex-learning/self-improve-run.json"
)"
if [ "$artifact_summary" != $'1\tfresh\t2\tOpenAI Python releases' ]; then
  echo "unexpected self-improve artifact external signal retirement summary: $artifact_summary" >&2
  exit 1
fi

echo "self improve resolved external signals task test passed"
