#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR="$(mktemp -d)"
REPO_ROOT="$TMP_DIR/repo"
EXTERNAL_WORKSPACE="$TMP_DIR/superheld-repo"

cleanup() {
  rm -rf "$TMP_DIR"
}

trap cleanup EXIT

recent_timestamp="$(
  python3 - <<'PY'
from datetime import datetime, timezone
print(datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"))
PY
)"

mkdir -p \
  "$REPO_ROOT/scripts" \
  "$REPO_ROOT/codex-memory" \
  "$REPO_ROOT/codex-learning" \
  "$REPO_ROOT/codex-logs" \
  "$REPO_ROOT/queues" \
  "$REPO_ROOT/projects/superheld" \
  "$EXTERNAL_WORKSPACE/.codex-agent" \
  "$EXTERNAL_WORKSPACE/packages/playbooks" \
  "$EXTERNAL_WORKSPACE/apps/web"
cp -R "$ROOT_DIR/scripts/." "$REPO_ROOT/scripts"

cat >"$REPO_ROOT/projects/superheld/spec.md" <<'EOF'
# Project Spec

project: superheld

## Milestone Seeds
```json
{
  "seeds": [
    {
      "milestone": "Satisfied seed.",
      "title": "Align credential recovery trigger coverage in account recovery playbook",
      "category": "code",
      "target_file": "packages/playbooks/account_recovery_after_credential_risk.json",
      "anchor": "trigger_event_types",
      "done_markers": [
        "credential_recovery_trigger"
      ],
      "reason_template": "Start with `{target_file}` at `{anchor}`."
    },
    {
      "milestone": "Unresolved seed.",
      "title": "Define incident state contract in web dashboard blueprint",
      "category": "learning",
      "target_file": "apps/web/README.md",
      "anchor": "## Core Cards",
      "done_markers": [
        "## Incident State Contract"
      ],
      "reason_template": "Start with `{target_file}` after `{anchor}`."
    }
  ]
}
```
EOF

cat >"$EXTERNAL_WORKSPACE/packages/playbooks/account_recovery_after_credential_risk.json" <<'EOF'
{
  "id": "account_recovery_after_credential_risk",
  "trigger_event_types": [
    "credential_risk_detected",
    "credential_recovery_trigger"
  ]
}
EOF

cat >"$EXTERNAL_WORKSPACE/apps/web/README.md" <<'EOF'
# Web

## Core Cards

- incident summary
- next safe action
EOF

cat >"$REPO_ROOT/codex-learning/metrics.json" <<'EOF'
{
  "success_rate": 0.9,
  "recent_success_rate": 0.9,
  "first_pass_success_rate": 0.9,
  "timeout_failure_rate": 0.0,
  "zero_step_timeout_rate": 0.0,
  "retry_classification_coverage": 1.0,
  "retry_classified_count": 2,
  "retry_total_count": 2,
  "approved_tasks": 0,
  "approved_backlog": 0,
  "pending_approval_tasks": 1,
  "queued_tasks": 0,
  "running_tasks": 0,
  "task_registry_payload_bytes": 16000,
  "task_registry_pressure_detected": false,
  "retry_churn_detected": false,
  "strategy_saturation_detected": false,
  "loop_effort_task_count": 0,
  "loop_effort_extra_step_attempts": 0,
  "external_signal_status": "fresh",
  "total_tasks": 8
}
EOF

cat >"$REPO_ROOT/codex-memory/tasks.json" <<'EOF'
{
  "tasks": []
}
EOF

cat >"$REPO_ROOT/codex-memory/tasks.log" <<EOF
{"timestamp":"$recent_timestamp","project":"superheld","task":"Baseline spec seed success","task_id":"success-1","result":"SUCCESS","attempt":1}
EOF

cat >"$EXTERNAL_WORKSPACE/.codex-agent/tasks.json" <<'EOF'
{
  "tasks": [
    {
      "id": "task-001-align-credential-recovery-trigger",
      "title": "Align credential recovery trigger coverage in account recovery playbook",
      "execution_task": "[self-improve:medium] Align credential recovery trigger coverage in account recovery playbook",
      "project": "superheld",
      "status": "pending_approval",
      "created_at": "2026-03-30T08:00:00Z",
      "updated_at": "2026-03-30T08:00:00Z",
      "task_intent": {
        "source": "self-improve",
        "objective": "Align credential recovery trigger coverage in account recovery playbook",
        "project": "superheld",
        "category": "code",
        "affected_files": [
          "packages/playbooks/account_recovery_after_credential_risk.json"
        ]
      },
      "target_files": [
        "packages/playbooks/account_recovery_after_credential_risk.json"
      ],
      "execution": {
        "state": "pending_approval",
        "attempt": 0,
        "max_retries": 2,
        "provider": "codex",
        "updated_at": "2026-03-30T08:00:00Z"
      },
      "history": [
        {
          "at": "2026-03-30T08:00:00Z",
          "action": "create",
          "from_status": "",
          "to_status": "pending_approval",
          "project": "superheld",
          "queue_task": "[self-improve:medium] Align credential recovery trigger coverage in account recovery playbook",
          "note": "Auto-generated by self-improve engine."
        }
      ]
    }
  ]
}
EOF

cat >"$REPO_ROOT/projects/superheld/project.json" <<EOF
{
  "project": "superheld",
  "project_id": "superheld",
  "workspace": "$EXTERNAL_WORKSPACE",
  "repo_url": "https://example.invalid/superheld",
  "memory_file": "$REPO_ROOT/projects/superheld/memory.md",
  "spec_file": "$REPO_ROOT/projects/superheld/spec.md",
  "policy_file": "$REPO_ROOT/projects/superheld/policy.json",
  "task_registry_file": "$EXTERNAL_WORKSPACE/.codex-agent/tasks.json"
}
EOF

(
  cd "$REPO_ROOT"
  IMPROVEMENT_COOLDOWN_SECONDS=0 \
  bash scripts/self-improve.sh superheld >/dev/null
)

(
  cd "$REPO_ROOT"
  IMPROVEMENT_COOLDOWN_SECONDS=0 \
  bash scripts/self-improve.sh superheld >/dev/null
)

old_status="$(
  jq -r '.tasks[] | select(.id == "task-001-align-credential-recovery-trigger") | .status' \
    "$EXTERNAL_WORKSPACE/.codex-agent/tasks.json"
)"
old_reason="$(
  jq -r '.tasks[] | select(.id == "task-001-align-credential-recovery-trigger") | .shelved_reason' \
    "$EXTERNAL_WORKSPACE/.codex-agent/tasks.json"
)"
new_pending_title="$(
  jq -r '.tasks[] | select(.id != "task-001-align-credential-recovery-trigger" and .status == "pending_approval") | .title' \
    "$EXTERNAL_WORKSPACE/.codex-agent/tasks.json"
)"
artifact_summary="$(
  jq -r '[.counts.submitted, .gating.submission_reason] | @tsv' \
    "$REPO_ROOT/codex-learning/self-improve-run.json"
)"

if [ "$old_status" != "shelved" ]; then
  echo "expected satisfied seed task to be shelved, got: $old_status" >&2
  exit 1
fi

if [[ "$old_reason" != auto-shelved:\ structured\ spec\ seed\ markers\ already\ present* ]]; then
  echo "expected structured seed shelve reason, got: $old_reason" >&2
  exit 1
fi

if [ "$new_pending_title" != "Define incident state contract in web dashboard blueprint" ]; then
  echo "expected next unresolved seed to be submitted, got: $new_pending_title" >&2
  exit 1
fi

if [ "$artifact_summary" != $'1\tdefault_limit' ]; then
  echo "unexpected artifact summary after resolved seed rollover: $artifact_summary" >&2
  exit 1
fi

echo "self improve external resolved structured seed rollover test passed"
