#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR="$(mktemp -d)"

cleanup() {
  rm -rf "$TMP_DIR"
}

trap cleanup EXIT

make_repo() {
  local repo_root="$1"
  mkdir -p "$repo_root"
  cp -R "$ROOT_DIR/scripts" "$repo_root/scripts"
  mkdir -p "$repo_root/codex-memory" "$repo_root/codex-learning" "$repo_root/codex-logs" "$repo_root/queues" "$repo_root/projects"
}

REPO_ROOT="$TMP_DIR/repo"
make_repo "$REPO_ROOT"

cat >"$REPO_ROOT/codex-memory/tasks.json" <<'EOF'
{
  "tasks": [
    {
      "id": "task-133-improve-retry-failure-classification-cov",
      "title": "Improve retry failure classification coverage",
      "project": "codex-agent-system",
      "status": "pending_approval",
      "strategy_template": "self_improvement",
      "source_task_id": "self-improve",
      "task_intent": {
        "source": "self-improve",
        "objective": "Improve retry failure classification coverage",
        "project": "codex-agent-system",
        "category": "learning",
        "context_hint": "Only 24% of retry failures are classified (15/62)."
      },
      "execution_task": "[self-improve:high] Improve retry failure classification coverage -- Only 24% of retry failures are classified (15/62)",
      "created_at": "2026-03-25T06:15:02Z",
      "updated_at": "2026-03-25T06:15:06Z",
      "history": [
        {
          "at": "2026-03-25T06:15:06Z",
          "action": "create",
          "from_status": "",
          "to_status": "pending_approval",
          "project": "codex-agent-system",
          "queue_task": "[self-improve:high] Improve retry failure classification coverage -- Only 24% of retry failures are classified (15/62)",
          "note": "Auto-generated by self-improve engine."
        }
      ]
    }
  ]
}
EOF

cat >"$REPO_ROOT/codex-memory/tasks.log" <<'EOF'
{"timestamp":"2026-03-25T03:00:00Z","project":"codex-agent-system","task":"Retry failure 01","result":"FAILURE","failure_kind":"timeout","task_id":"retry-01"}
{"timestamp":"2026-03-25T03:01:00Z","project":"codex-agent-system","task":"Retry failure 02","result":"FAILURE","failure_kind":"timeout","task_id":"retry-02"}
{"timestamp":"2026-03-25T03:02:00Z","project":"codex-agent-system","task":"Recovered task","result":"SUCCESS","task_id":"retry-03"}
EOF

cat >"$REPO_ROOT/codex-learning/metrics.json" <<'EOF'
{
  "success_rate": 0.82,
  "recent_success_rate": 0.8,
  "timeout_failure_rate": 0.04,
  "first_pass_success_rate": 0.78,
  "retry_classification_coverage": 0.87,
  "retry_classified_count": 54,
  "retry_total_count": 62,
  "approved_tasks": 0,
  "pending_approval_tasks": 1,
  "approved_backlog": 0,
  "task_registry_pressure_bytes": 64000,
  "strategy_saturation": false,
  "zero_step_timeout_rate": 0.05
}
EOF

cat >"$REPO_ROOT/codex-learning/retry-failure-analysis.jsonl" <<'EOF'
{"task_id":"retry-01","project":"codex-agent-system","attempt":2,"failed_step_index":1,"classification":"timeout","timestamp":"2026-03-25T03:20:00Z"}
EOF

cat >"$REPO_ROOT/codex-learning/external-signals.json" <<'EOF'
{}
EOF

python3 - "$REPO_ROOT/codex-learning/metrics.json" <<'PY'
import os
import sys
import time

metrics_path = sys.argv[1]
future = time.time() + 60
os.utime(metrics_path, (future, future))
PY

(
  cd "$REPO_ROOT"
  IMPROVEMENT_COOLDOWN_SECONDS=0 bash scripts/self-improve.sh codex-agent-system >/dev/null
)

task_summary="$(
  jq -r '
    .tasks
    | map(select(.id == "task-133-improve-retry-failure-classification-cov"))
    | first
    | [
        .status,
        .shelved_reason,
        .history[-1].action,
        .history[-1].to_status
      ] | @tsv
  ' "$REPO_ROOT/codex-memory/tasks.json"
)"
if [ "$task_summary" != $'shelved\tauto-shelved: retry classification coverage recovered to 100% (1/1)\tauto_shelve\tshelved' ]; then
  echo "unexpected resolved retry-classification task summary: $task_summary" >&2
  exit 1
fi

same_title_pending_count="$(
  jq -r '
    [
      .tasks[]
      | select(
          (.title // "") == "Improve retry failure classification coverage"
          and (.status // "") == "pending_approval"
        )
    ] | length
  ' "$REPO_ROOT/codex-memory/tasks.json"
)"
if [ "$same_title_pending_count" != "0" ]; then
  echo "expected stale retry classification task family to leave pending approval" >&2
  exit 1
fi

artifact_summary="$(
  jq -r '
    [
      (.gating.retired_resolved_pending_tasks // 0)
    ] | @tsv
  ' "$REPO_ROOT/codex-learning/self-improve-run.json"
)"
if [ "$artifact_summary" != $'1' ]; then
  echo "unexpected self-improve artifact retirement summary: $artifact_summary" >&2
  exit 1
fi

echo "self improve resolved retry classification task test passed"
